import type { Metadata } from "next";
import './globals.css';
import { Lexend_Mega } from "next/font/google";

const lexendMega = Lexend_Mega({ 
  subsets: ['latin'], 
  weight: '700'  // bold
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexendMega.className} font-sans font-bold`}
      >
        {children}
      </body>
    </html>
  );
}
